# Generated by Django 4.2.3 on 2023-12-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Potato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(choices=[('10-26-26', '10-26-26'), ('14-35-14', '14-35-14'), ('17-17-17', '17-17-17'), ('20-20', '20-20'), ('28-28', '28-28'), ('DAP', 'DAP'), ('Urea', 'Urea')], max_length=10),
        ),
    ]
