# Generated by Django 4.2.3 on 2023-12-02 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Potato', '0002_alter_picture_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('apple', 'apple'), ('pear', 'pear'), ('cherry', 'cherry'), ('banana', 'banana'), ('plantain', 'plantain'), ('papaya', 'papaya'), ('blackgram', 'blackgram'), ('green gram', 'green gram'), ('lentil', 'lentil'), ('chickpea', 'chickpea'), ('fava bean', 'fava bean'), ('soybean', 'soybean'), ('coconut', 'coconut'), ('oil palm', 'oil palm'), ('betel nut', 'betel nut'), ('coffee', 'coffee'), ('cocoa', 'cocoa'), ('tea', 'tea'), ('cotton', 'cotton'), ('flax', 'flax'), ('hemp', 'hemp'), ('grapes', 'grapes'), ('wineberries', 'wineberries'), ('kiwi', 'kiwi'), ('jute', 'jute'), ('sisal', 'sisal'), ('flax', 'flax'), ('kidneybeans', 'kidneybeans'), ('navy beans', 'navy beans'), ('lima beans', 'lima beans'), ('lentil', 'lentil'), ('chickpea', 'chickpea'), ('blackgram', 'blackgram'), ('maize', 'maize'), ('wheat', 'wheat'), ('barley', 'barley'), ('mango', 'mango'), ('guava', 'guava'), ('papaya', 'papaya'), ('mothbeans', 'mothbeans'), ('blackgram', 'blackgram'), ('green gram', 'green gram'), ('mungbean', 'mungbean'), ('blackgram', 'blackgram'), ('mothbeans', 'mothbeans'), ('muskmelon', 'muskmelon'), ('cucumber', 'cucumber'), ('pumpkin', 'pumpkin'), ('orange', 'orange'), ('lemon', 'lemon'), ('lime', 'lime'), ('papaya', 'papaya'), ('mango', 'mango'), ('guava', 'guava'), ('pigeonpeas', 'pigeonpeas'), ('lentil', 'lentil'), ('chickpea', 'chickpea'), ('pomegranate', 'pomegranate'), ('fig', 'fig'), ('quince', 'quince'), ('rice', 'rice'), ('barley', 'barley'), ('wheat', 'wheat'), ('watermelon', 'watermelon'), ('cantaloupe', 'cantaloupe'), ('cucumber', 'cucumber')], max_length=1000)),
                ('preview', models.ImageField(upload_to='static/images')),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_sizes', models.TextField(max_length=500)),
                ('captured_time', models.DateField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Potato.allplants')),
            ],
        ),
    ]
